version: 2.1

executors:
  default:
    working_directory: ~/rostjob
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.2
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'wbnfvtufkjdbhec'
      - image:  circleci/redis:4.0

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - rostjob-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - rostjob-
      - configure_bundler
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Setup redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: set config DB rails
          command: mv config/database.yml.example config/database.yml
      - run: touch config/master.key
      - run: echo "aca38128b2818f79cc1381ef54d951dc" > config/master.key
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load --trace
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: mkdir ~/rspec
      - run:
          name: RSpec tests
          command: bundle exec rspec spec/interactors/ --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec
      - save_cache:
          key: rostjob-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - ./rostjob

workflows:
  version: 2
  integration:
    jobs:
      - build