<% host = Gem.win_platform? ? '127.0.0.1:6379': 'localhost:6379' %>
defaults: &defaults
  redis:
    host: <%= "redis://#{host}/1" %>

development:
  <<: *defaults

test:
  <<: *defaults
  redis:
    host: <%= "redis://#{host}/2" %>

production:
  <<: *defaults

staging:
  <<: *defaults
