defaults: &defaults
  redis:
    host: redis://localhost:6379/1

development:
  <<: *defaults

test:
  <<: *defaults
  redis:
    host: redis://localhost:6379/2

production:
  <<: *defaults

staging:
  <<: *defaults
