defaults: &defaults
  redis:
    host: redis://127.0.0.1:6379/1

development:
  <<: *defaults

test:
  <<: *defaults
  redis:
    host: redis://127.0.0.1:6379/2

production:
  <<: *defaults

staging:
  <<: *defaults
