check_interview_deadline:
  cron: '00 10 * * *'
  class: 'CheckInterviewDeadlineJob'
  queue: critical
  description: 'Creates jobs for check interview deadline'

warranty_period_processing:
  cron: "*/5 * * * *"
  class: "CreateWarrantyPeriodProcessingJob"
  queue: critical
  description: "Creates jobs for warranty period processing"

super_job_fetch_resumes:
  cron: "30 0 * * *"
  class: "CreateFetchResumesFromSuperJob"
  queue: critical
  description: "Fetch resumes from SuperJob"

careerist_job_fetch_resumes:
  cron: "30 0 * * *"
  class: "CreateFetchResumesFromCareeristJob"
  queue: critical
  description: "Fetch resumes from CareeristJob"

#generate_payment_orders_for_companies:
#  cron: "15 1 * * *"
#  class: "CreateGeneratePaymentOrderForCompaniesJob"
#  queue: critical
#  description: "Creates jobs for generating payment orders for companies"
#generate_payment_orders_for_private_persons:
#  cron: "30 1 * * *"
#  class: "CreateGeneratePaymentOrderForPrivatePersonsJob"
#  queue: critical
#  description: "Creates jobs for generating payment orders for private persons"
#generate_tax_payment_orders:
#  cron: "45 1 * * *"
#  class: "GenerateTaxPaymentOrderJob"
#  queue: critical
#  description: "Creates job for generating payment order to pay NDFL tax"

every_day_mail_processing_job:
  cron: "00 7 * * *"
  class: "SendingEveryDayMailCustomerJob"
  queue: critical
  description: "Send every day mails for customer"

every_day_mail_for_contractor_processing_job:
  cron: "00 9 * * *"
  class: "SendingEveryDayMailContractorJob"
  queue: critical
  description: "Send every day mails for contractor"

